# Generated by Django 5.2.5 on 2025-08-15 22:17

import core.models
import pictures.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_equipe_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='imagem',
            field=pictures.models.PictureField(aspect_ratios=[None, '1/1'], breakpoints={'desktop': 992, 'mobile': 576, 'tablet': 768, 'thumb': 480}, container_width=1200, file_types=['PNG'], grid_columns=12, height_field='image_height', pixel_densities=[1, 2], upload_to=core.models.get_file_path, width_field='image_width'),
        ),
    ]
