# Generated by Django 5.2.5 on 2025-08-16 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_servico_icone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cargo', verbose_name='Cargo'),
        ),
    ]
