# Generated by Django 5.2.5 on 2025-08-20 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_equipe_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='bio',
            field=models.TextField(max_length=200, verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='image_height',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='image_width',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='servico',
            name='descricao',
            field=models.TextField(max_length=200, verbose_name='Descrição'),
        ),
    ]
